-- ============================================================================
-- DATA CONTRACT REGISTRY - SNOWFLAKE SETUP
-- ============================================================================
-- This script creates the contract registry infrastructure in Snowflake.
-- Run as ACCOUNTADMIN or a role with CREATE DATABASE privileges.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- DATABASE & SCHEMA SETUP
-- ─────────────────────────────────────────────────────────────────────────────

USE ROLE ACCOUNTADMIN;

-- Create governance database if not exists
CREATE DATABASE IF NOT EXISTS GOVERNANCE;

-- Set database context
USE DATABASE GOVERNANCE;

-- Create contract registry schema
CREATE SCHEMA IF NOT EXISTS CONTRACT_REGISTRY;

-- Create observability schema for monitoring views
CREATE SCHEMA IF NOT EXISTS OBSERVABILITY;

-- Set schema context
USE SCHEMA CONTRACT_REGISTRY;

-- ─────────────────────────────────────────────────────────────────────────────
-- CONTRACT REGISTRY TABLES
-- ─────────────────────────────────────────────────────────────────────────────

-- Core contracts table
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.CONTRACTS (
    CONTRACT_ID VARCHAR(128) NOT NULL,
    CONTRACT_TYPE VARCHAR(20) NOT NULL,  -- 'data' or 'product'
    VERSION VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'draft',
    PRODUCER_SYSTEM VARCHAR(256),
    PRODUCER_TEAM VARCHAR(256),
    PRODUCER_EMAIL VARCHAR(256),
    DESCRIPTION TEXT,
    YAML_DEFINITION VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(256) DEFAULT CURRENT_USER(),
    UPDATED_BY VARCHAR(256) DEFAULT CURRENT_USER(),
    PRIMARY KEY (CONTRACT_ID, VERSION)
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.CONTRACTS IS 
'Central registry of all data and product contracts';

-- Contract version history
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_VERSIONS (
    VERSION_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    VERSION VARCHAR(20) NOT NULL,
    PREVIOUS_VERSION VARCHAR(20),
    CHANGE_TYPE VARCHAR(20) NOT NULL,  -- 'major', 'minor', 'patch'
    CHANGE_DESCRIPTION TEXT,
    BREAKING_CHANGES ARRAY,
    YAML_DEFINITION VARIANT,
    STATUS VARCHAR(20) DEFAULT 'pending',  -- 'pending', 'approved', 'deployed', 'rolled_back'
    DEPLOYED_AT TIMESTAMP_NTZ,
    DEPLOYED_BY VARCHAR(256),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(256) DEFAULT CURRENT_USER()
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_VERSIONS IS 
'Version history for all contracts with change tracking';

-- Contract column definitions
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_COLUMNS (
    COLUMN_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    VERSION VARCHAR(20) NOT NULL,
    COLUMN_NAME VARCHAR(256) NOT NULL,
    DATA_TYPE VARCHAR(128),
    DESCRIPTION TEXT,
    IS_NULLABLE BOOLEAN DEFAULT TRUE,
    IS_PRIMARY_KEY BOOLEAN DEFAULT FALSE,
    IS_SYSTEM_MANAGED BOOLEAN DEFAULT FALSE,
    CONSTRAINTS ARRAY,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_COLUMNS IS 
'Column-level definitions for each contract version';

-- Column tags
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.COLUMN_TAGS (
    TAG_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    COLUMN_ID VARCHAR(64) NOT NULL,
    TAG_NAME VARCHAR(128) NOT NULL,
    TAG_VALUE VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.COLUMN_TAGS IS 
'Governance tags applied to contract columns';

-- Consumer registrations
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_CONSUMERS (
    CONSUMER_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    CONSUMER_TEAM VARCHAR(256) NOT NULL,
    CONSUMER_EMAIL VARCHAR(256) NOT NULL,
    SLACK_CHANNEL VARCHAR(128),
    USE_CASE TEXT,
    ACCESS_LEVEL VARCHAR(50),
    REQUIRED_COLUMNS ARRAY,
    NOTIFY_BREAKING BOOLEAN DEFAULT TRUE,
    NOTIFY_DEPRECATION BOOLEAN DEFAULT TRUE,
    NOTIFY_MINOR BOOLEAN DEFAULT FALSE,
    ACKNOWLEDGED_VERSION VARCHAR(20),
    REGISTERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REGISTERED_BY VARCHAR(256) DEFAULT CURRENT_USER(),
    LAST_ACKNOWLEDGED_AT TIMESTAMP_NTZ
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_CONSUMERS IS 
'Registry of teams consuming each contract';

-- SLA definitions
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_SLAS (
    SLA_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    VERSION VARCHAR(20) NOT NULL,
    SLA_TYPE VARCHAR(50) NOT NULL,  -- 'freshness', 'completeness', 'availability', 'volume'
    METRIC_NAME VARCHAR(128),
    THRESHOLD_VALUE FLOAT,
    THRESHOLD_UNIT VARCHAR(32),
    MEASUREMENT_SQL TEXT,
    SEVERITY VARCHAR(20) DEFAULT 'warning',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_SLAS IS 
'SLA definitions for each contract';

-- Quality rules
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.QUALITY_RULES (
    RULE_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    VERSION VARCHAR(20) NOT NULL,
    RULE_NAME VARCHAR(256) NOT NULL,
    RULE_TYPE VARCHAR(50) NOT NULL,  -- 'column_check', 'table_check', 'cross_table_check'
    TARGET_COLUMN VARCHAR(256),
    RULE_SQL TEXT NOT NULL,
    SEVERITY VARCHAR(20) DEFAULT 'warning',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.QUALITY_RULES IS 
'Data quality rules defined in contracts';

-- Quality rule execution results
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.QUALITY_RULE_RESULTS (
    RESULT_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    RULE_ID VARCHAR(64) NOT NULL,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    EXECUTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PASSED BOOLEAN,
    RESULT_VALUE VARIANT,
    ERROR_MESSAGE TEXT,
    ROWS_CHECKED NUMBER,
    ROWS_FAILED NUMBER
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.QUALITY_RULE_RESULTS IS 
'Execution history of quality rules';

-- SLA metrics
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.SLA_METRICS (
    METRIC_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    SLA_ID VARCHAR(64) NOT NULL,
    MEASURED_VALUE FLOAT,
    THRESHOLD_VALUE FLOAT,
    IS_VIOLATION BOOLEAN,
    VIOLATION_SEVERITY VARCHAR(20),
    MEASURED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.SLA_METRICS IS 
'SLA measurement history';

-- Breaking change approvals
CREATE TABLE IF NOT EXISTS GOVERNANCE.CONTRACT_REGISTRY.BREAKING_CHANGE_APPROVALS (
    APPROVAL_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CONTRACT_ID VARCHAR(128) NOT NULL,
    FROM_VERSION VARCHAR(20) NOT NULL,
    TO_VERSION VARCHAR(20) NOT NULL,
    CONSUMER_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'pending',  -- 'pending', 'acknowledged', 'objected'
    RESPONSE_COMMENT TEXT,
    OBJECTION_REASON TEXT,
    NOTIFIED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESPONDED_AT TIMESTAMP_NTZ,
    DEADLINE_AT TIMESTAMP_NTZ
);

COMMENT ON TABLE GOVERNANCE.CONTRACT_REGISTRY.BREAKING_CHANGE_APPROVALS IS 
'Tracking consumer acknowledgments for breaking changes';

-- ─────────────────────────────────────────────────────────────────────────────
-- VIEWS
-- ─────────────────────────────────────────────────────────────────────────────

-- Active contracts view
CREATE OR REPLACE VIEW GOVERNANCE.CONTRACT_REGISTRY.VW_ACTIVE_CONTRACTS AS
SELECT 
    c.CONTRACT_ID,
    c.CONTRACT_TYPE,
    c.VERSION,
    c.PRODUCER_SYSTEM,
    c.PRODUCER_TEAM,
    c.PRODUCER_EMAIL,
    c.DESCRIPTION,
    c.CREATED_AT,
    c.UPDATED_AT,
    COUNT(DISTINCT con.CONSUMER_ID) AS CONSUMER_COUNT,
    COUNT(DISTINCT col.COLUMN_ID) AS COLUMN_COUNT
FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACTS c
LEFT JOIN GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_CONSUMERS con 
    ON c.CONTRACT_ID = con.CONTRACT_ID
LEFT JOIN GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_COLUMNS col 
    ON c.CONTRACT_ID = col.CONTRACT_ID AND c.VERSION = col.VERSION
WHERE c.STATUS = 'active'
GROUP BY 
    c.CONTRACT_ID, c.CONTRACT_TYPE, c.VERSION, c.PRODUCER_SYSTEM,
    c.PRODUCER_TEAM, c.PRODUCER_EMAIL, c.DESCRIPTION, c.CREATED_AT, c.UPDATED_AT;

-- Contracts with pending breaking changes
CREATE OR REPLACE VIEW GOVERNANCE.CONTRACT_REGISTRY.VW_PENDING_BREAKING_CHANGES AS
SELECT 
    cv.CONTRACT_ID,
    cv.VERSION AS NEW_VERSION,
    cv.PREVIOUS_VERSION,
    cv.CHANGE_DESCRIPTION,
    cv.BREAKING_CHANGES,
    cv.CREATED_AT AS PROPOSED_AT,
    cv.CREATED_BY AS PROPOSED_BY,
    COUNT(CASE WHEN bca.STATUS = 'pending' THEN 1 END) AS PENDING_APPROVALS,
    COUNT(CASE WHEN bca.STATUS = 'acknowledged' THEN 1 END) AS ACKNOWLEDGED,
    COUNT(CASE WHEN bca.STATUS = 'objected' THEN 1 END) AS OBJECTIONS
FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_VERSIONS cv
LEFT JOIN GOVERNANCE.CONTRACT_REGISTRY.BREAKING_CHANGE_APPROVALS bca
    ON cv.CONTRACT_ID = bca.CONTRACT_ID 
    AND cv.VERSION = bca.TO_VERSION
WHERE cv.CHANGE_TYPE = 'major'
  AND cv.STATUS = 'pending'
GROUP BY 
    cv.CONTRACT_ID, cv.VERSION, cv.PREVIOUS_VERSION, 
    cv.CHANGE_DESCRIPTION, cv.BREAKING_CHANGES, cv.CREATED_AT, cv.CREATED_BY;

-- Consumer dependencies view
CREATE OR REPLACE VIEW GOVERNANCE.CONTRACT_REGISTRY.VW_CONSUMER_DEPENDENCIES AS
SELECT 
    c.CONTRACT_ID,
    c.VERSION,
    c.STATUS,
    con.CONSUMER_TEAM,
    con.CONSUMER_EMAIL,
    con.USE_CASE,
    con.ACCESS_LEVEL,
    con.REQUIRED_COLUMNS,
    con.NOTIFY_BREAKING,
    con.ACKNOWLEDGED_VERSION,
    CASE 
        WHEN con.ACKNOWLEDGED_VERSION = c.VERSION THEN 'current'
        WHEN con.ACKNOWLEDGED_VERSION IS NULL THEN 'never_acknowledged'
        ELSE 'behind'
    END AS ACKNOWLEDGMENT_STATUS
FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACTS c
JOIN GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_CONSUMERS con
    ON c.CONTRACT_ID = con.CONTRACT_ID
WHERE c.STATUS = 'active';

-- ─────────────────────────────────────────────────────────────────────────────
-- OBSERVABILITY VIEWS
-- ─────────────────────────────────────────────────────────────────────────────

-- Contract health dashboard
CREATE OR REPLACE VIEW GOVERNANCE.OBSERVABILITY.VW_CONTRACT_HEALTH AS
SELECT 
    c.CONTRACT_ID,
    c.CONTRACT_TYPE,
    c.VERSION,
    c.PRODUCER_TEAM,
    c.STATUS,
    -- Quality score (% of rules passing in last 24 hours)
    COALESCE(
        (SELECT ROUND(100.0 * SUM(CASE WHEN qrr.PASSED THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1)
         FROM GOVERNANCE.CONTRACT_REGISTRY.QUALITY_RULE_RESULTS qrr
         JOIN GOVERNANCE.CONTRACT_REGISTRY.QUALITY_RULES qr ON qrr.RULE_ID = qr.RULE_ID
         WHERE qr.CONTRACT_ID = c.CONTRACT_ID
           AND qrr.EXECUTION_TIME > DATEADD('hour', -24, CURRENT_TIMESTAMP())),
        NULL
    ) AS QUALITY_SCORE_PCT,
    -- SLA compliance (% of SLAs met in last 24 hours)
    COALESCE(
        (SELECT ROUND(100.0 * SUM(CASE WHEN NOT sm.IS_VIOLATION THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1)
         FROM GOVERNANCE.CONTRACT_REGISTRY.SLA_METRICS sm
         WHERE sm.CONTRACT_ID = c.CONTRACT_ID
           AND sm.MEASURED_AT > DATEADD('hour', -24, CURRENT_TIMESTAMP())),
        NULL
    ) AS SLA_COMPLIANCE_PCT,
    -- Consumer count
    (SELECT COUNT(*) FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_CONSUMERS con 
     WHERE con.CONTRACT_ID = c.CONTRACT_ID) AS CONSUMER_COUNT,
    -- Pending acknowledgments
    (SELECT COUNT(*) FROM GOVERNANCE.CONTRACT_REGISTRY.BREAKING_CHANGE_APPROVALS bca
     WHERE bca.CONTRACT_ID = c.CONTRACT_ID AND bca.STATUS = 'pending') AS PENDING_ACKNOWLEDGMENTS
FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACTS c
WHERE c.STATUS = 'active';

-- Missing tags report
CREATE OR REPLACE VIEW GOVERNANCE.OBSERVABILITY.VW_MISSING_GOVERNANCE_TAGS AS
SELECT 
    cc.CONTRACT_ID,
    cc.VERSION,
    cc.COLUMN_NAME,
    CASE WHEN MAX(CASE WHEN ct.TAG_NAME = 'DATA_CLASSIFICATION' THEN 1 ELSE 0 END) = 0 
         THEN TRUE ELSE FALSE END AS MISSING_DATA_CLASSIFICATION,
    CASE WHEN MAX(CASE WHEN ct.TAG_NAME = 'PII_TYPE' THEN 1 ELSE 0 END) = 0 
         THEN TRUE ELSE FALSE END AS MISSING_PII_TYPE,
    CASE WHEN MAX(CASE WHEN ct.TAG_NAME = 'AI_ALLOWED' THEN 1 ELSE 0 END) = 0 
         THEN TRUE ELSE FALSE END AS MISSING_AI_ALLOWED
FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_COLUMNS cc
LEFT JOIN GOVERNANCE.CONTRACT_REGISTRY.COLUMN_TAGS ct ON cc.COLUMN_ID = ct.COLUMN_ID
WHERE cc.IS_SYSTEM_MANAGED = FALSE
GROUP BY cc.CONTRACT_ID, cc.VERSION, cc.COLUMN_NAME
HAVING MISSING_DATA_CLASSIFICATION OR MISSING_PII_TYPE OR MISSING_AI_ALLOWED;

-- ─────────────────────────────────────────────────────────────────────────────
-- STORED PROCEDURES
-- ─────────────────────────────────────────────────────────────────────────────

-- Register a new contract from YAML
CREATE OR REPLACE PROCEDURE GOVERNANCE.CONTRACT_REGISTRY.REGISTER_CONTRACT(
    P_CONTRACT_YAML TEXT
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_contract_id VARCHAR;
    v_version VARCHAR;
    v_contract_type VARCHAR;
    v_yaml VARIANT;
BEGIN
    -- Parse YAML (stored as VARIANT)
    v_yaml := PARSE_JSON(P_CONTRACT_YAML);
    
    -- Determine contract type and extract ID/version
    IF (v_yaml:contract IS NOT NULL) THEN
        v_contract_type := 'data';
        v_contract_id := v_yaml:contract:id::VARCHAR;
        v_version := v_yaml:contract:version::VARCHAR;
    ELSIF (v_yaml:product IS NOT NULL) THEN
        v_contract_type := 'product';
        v_contract_id := v_yaml:product:id::VARCHAR;
        v_version := v_yaml:product:version::VARCHAR;
    ELSE
        RETURN 'ERROR: Invalid contract format - missing contract or product key';
    END IF;
    
    -- Insert or update contract
    MERGE INTO GOVERNANCE.CONTRACT_REGISTRY.CONTRACTS tgt
    USING (SELECT :v_contract_id AS cid, :v_version AS ver) src
    ON tgt.CONTRACT_ID = src.cid AND tgt.VERSION = src.ver
    WHEN MATCHED THEN
        UPDATE SET 
            YAML_DEFINITION = :v_yaml,
            UPDATED_AT = CURRENT_TIMESTAMP(),
            UPDATED_BY = CURRENT_USER()
    WHEN NOT MATCHED THEN
        INSERT (CONTRACT_ID, CONTRACT_TYPE, VERSION, STATUS, YAML_DEFINITION)
        VALUES (:v_contract_id, :v_contract_type, :v_version, 'draft', :v_yaml);
    
    RETURN 'Contract registered: ' || v_contract_id || ' v' || v_version;
END;
$$;

-- Notify consumers of breaking change
CREATE OR REPLACE PROCEDURE GOVERNANCE.CONTRACT_REGISTRY.NOTIFY_BREAKING_CHANGE(
    P_CONTRACT_ID VARCHAR,
    P_FROM_VERSION VARCHAR,
    P_TO_VERSION VARCHAR,
    P_DEADLINE_DAYS INT DEFAULT 14
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_consumer_count INT DEFAULT 0;
    c1 CURSOR FOR 
        SELECT COUNT(*) AS cnt
        FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_CONSUMERS
        WHERE CONTRACT_ID = ?
          AND NOTIFY_BREAKING = TRUE;
BEGIN
    -- Get count of consumers to notify
    OPEN c1 USING (P_CONTRACT_ID);
    FETCH c1 INTO v_consumer_count;
    CLOSE c1;
    
    -- Insert approval requests for all consumers who want breaking change notifications
    INSERT INTO GOVERNANCE.CONTRACT_REGISTRY.BREAKING_CHANGE_APPROVALS
        (APPROVAL_ID, CONTRACT_ID, FROM_VERSION, TO_VERSION, CONSUMER_ID, STATUS, DEADLINE_AT)
    SELECT 
        UUID_STRING(),
        P_CONTRACT_ID,
        P_FROM_VERSION,
        P_TO_VERSION,
        CONSUMER_ID,
        'pending',
        DATEADD('day', P_DEADLINE_DAYS, CURRENT_TIMESTAMP())
    FROM GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_CONSUMERS
    WHERE CONTRACT_ID = P_CONTRACT_ID
      AND NOTIFY_BREAKING = TRUE;
    
    RETURN 'Created ' || v_consumer_count::VARCHAR || ' approval requests for contract ' || P_CONTRACT_ID;
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- ROLES & GRANTS
-- ─────────────────────────────────────────────────────────────────────────────

-- Create contract admin role
CREATE ROLE IF NOT EXISTS CONTRACT_ADMIN;
GRANT USAGE ON DATABASE GOVERNANCE TO ROLE CONTRACT_ADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_ADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_ADMIN;
GRANT ALL ON ALL VIEWS IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_ADMIN;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_ADMIN;

-- Create contract viewer role (read-only)
CREATE ROLE IF NOT EXISTS CONTRACT_VIEWER;
GRANT USAGE ON DATABASE GOVERNANCE TO ROLE CONTRACT_VIEWER;
GRANT USAGE ON SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_VIEWER;
GRANT USAGE ON SCHEMA GOVERNANCE.OBSERVABILITY TO ROLE CONTRACT_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.OBSERVABILITY TO ROLE CONTRACT_VIEWER;

-- Create contract producer role
CREATE ROLE IF NOT EXISTS CONTRACT_PRODUCER;
GRANT USAGE ON DATABASE GOVERNANCE TO ROLE CONTRACT_PRODUCER;
GRANT USAGE ON SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_PRODUCER;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_PRODUCER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY TO ROLE CONTRACT_PRODUCER;
GRANT INSERT, UPDATE ON GOVERNANCE.CONTRACT_REGISTRY.CONTRACTS TO ROLE CONTRACT_PRODUCER;
GRANT INSERT ON GOVERNANCE.CONTRACT_REGISTRY.CONTRACT_VERSIONS TO ROLE CONTRACT_PRODUCER;
GRANT USAGE ON PROCEDURE GOVERNANCE.CONTRACT_REGISTRY.REGISTER_CONTRACT(TEXT) TO ROLE CONTRACT_PRODUCER;

-- Grant to existing roles (adjust as needed)
-- GRANT ROLE CONTRACT_ADMIN TO ROLE GOVERNANCE_ADMIN;
-- GRANT ROLE CONTRACT_VIEWER TO ROLE DATA_ANALYST;
-- GRANT ROLE CONTRACT_PRODUCER TO ROLE DOMAIN_OWNER;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────────
-- VERIFICATION
-- ─────────────────────────────────────────────────────────────────────────────

SELECT 'Contract Registry Setup Complete' AS STATUS;

SHOW TABLES IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY;
SHOW VIEWS IN SCHEMA GOVERNANCE.CONTRACT_REGISTRY;
SHOW VIEWS IN SCHEMA GOVERNANCE.OBSERVABILITY;
